### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pepper15** [unicornbloods/BeyondBeliefVanillaReborn#11] opened 2020-05-08 10:12 UTC
**Minecraft version:** 1.15.2 running with forge 31.1.77

**Optifine version:** OptiFine 1.15.2 HD U G1 pre16

**Shader version:** BBVR_Rewritev3

**Graphics card:** RTX 2060

**Operating system:** Win10

**Description of the bug:**
See for yourself, on screenshot, everything in nether renders like blank white canvas, playing on server, tested in singleplayer (same) and without forge (same results).
**Screenshots if any (Visual errors):**
![2020-05-08_12 05 43](https://user-images.githubusercontent.com/12576725/81395679-5a6a7d80-9124-11ea-9087-92b6152e7eee.png)
![2020-05-08_12 06 07](https://user-images.githubusercontent.com/12576725/81395683-5c344100-9124-11ea-9883-ac052471d6b1.png)

**latest.log if any (OpenGL errors):**
[2020-05-08-1.log.gz](https://github.com/unicornbloods/BeyondBeliefVanillaReborn/files/4598367/2020-05-08-1.log.gz)
[debug-1.log.gz](https://github.com/unicornbloods/BeyondBeliefVanillaReborn/files/4598369/debug-1.log.gz)

**Comment by unicornbloods** [comment] 2020-05-09 00:11
Duplicate of https://github.com/unicornbloods/BeyondBeliefVanillaReborn/issues/10 but thanks! Will fix today

**Closed as completed by unicornbloods** 2020-05-09 00:11 UTC
Labels: bug
